export default [
  {
    parentId: 0,
    id: 1,
    name: 'department',
    icon: '',
    path: '/components',
    component: '',
    routes: [
      {
        parentId: 1,
        id: 2,
        name: 'summary',
        icon: '',
        path: '/components/:cname/:vid/summary',
        component: 'components/summary/index',
        exact: true,
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 10,
        name: 'zeroday',
        icon: '',
        path: '/components/:cname/:vid/zeroday',
        component: 'components/zeroday/index',
        exact: true,
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 11,
        name: 'mobile',
        icon: '',
        path: '/components/:cname/:vid/mobile',
        component: 'components/mobile/index',
        exact: true,
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 12,
        name: 'public',
        icon: '',
        path: '/components/:cname/:vid/public',
        component: 'components/public/index',
        exact: true,
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 13,
        name: 'security',
        icon: '',
        path: '/components/:cname/:vid/security',
        component: 'components/security/index',
        exact: true,
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 14,
        name: 'leakage',
        icon: '',
        path: '/components/:cname/:vid/leakage',
        component: 'components/leakage/index',
        exact: true,
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 15,
        name: 'compliance',
        icon: '',
        path: '/components/:cname/:vid/compliance',
        component: 'components/compliance/index',
        exact: true,
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 16,
        name: 'malware',
        icon: '',
        path: '/components/:cname/:vid/malware',
        component: 'components/malware/index',
        exact: true,
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 17,
        name: 'misconfiguration',
        icon: '',
        path: '/components/:cname/:vid/misconfiguration',
        component: 'components/misconfiguration/index',
        exact: true,
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 18,
        name: 'password',
        icon: '',
        path: '/components/:cname/:vid/password',
        component: 'components/password/index',
        exact: true,
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 19,
        name: 'files',
        icon: '',
        path: '/components/:cname/:vid/files',
        component: 'components/files/index',
        exact: true,
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 20,
        name: 'packages',
        icon: '',
        path: '/components/:cname/:vid/packages',
        component: 'components/packages/index',
        exact: true,
        hideInMenu: true,
      },      
      {
        parentId: 1,
        id: 21,
        name: 'licenses',
        icon: '',
        path: '/components/:cname/:vid/licenses',
        component: 'components/licenses/index',
        exact: true,
        hideInMenu: true,
      },

      {
        parentId: 1,
        id: 30,
        name: 'zeroday-detail',
        icon: '',
        path: '/components/:cname/:vid/:tid/zeroday',
        component: 'components/zeroday-detail/index',
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 31,
        name: 'mobile-detail',
        icon: '',
        path: '/components/:cname/:vid/:tid/mobile',
        component: 'components/mobile-detail/index',
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 32,
        name: 'public-detail',
        icon: '',
        path: '/components/:cname/:vid/:tid/public',
        component: 'components/public-detail/index',
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 33,
        name: 'security-detail',
        icon: '',
        path: '/components/:cname/:vid/:tid/security',
        component: 'components/security-detail/index',
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 34,
        name: 'leakage-detail',
        icon: '',
        path: '/components/:cname/:vid/:tid/leakage',
        component: 'components/leakage-detail/index',
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 35,
        name: 'password-detail',
        icon: '',
        path: '/components/:cname/:vid/:tid/password',
        component: 'components/password-detail/index',
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 36,
        name: 'compliance-detail',
        icon: '',
        path: '/components/:cname/:vid/:tid/compliance',
        component: 'components/compliance-detail/index',
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 37,
        name: 'misconfiguration-detail',
        icon: '',
        path: '/components/:cname/:vid/:tid/misconfiguration',
        component: 'components/misconfiguration-detail/index',
        hideInMenu: true,
      },      
      {
        parentId: 1,
        id: 38,
        name: 'file-detail',
        icon: '',
        path: '/components/:cname/:vid/:uid/file',
        component: 'components/file-detail/index',
        hideInMenu: true,
      },
      {
        parentId: 1,
        id: 39,
        name: 'package-detail',
        icon: '',
        path: '/components/:cname/:vid/:uid/package',
        component: 'components/package-detail/index',
        hideInMenu: true,
      },

      {
        parentId: 1,
        id: 3,
        name: 'version',
        icon: '',
        path: '/components/:cname/:id',
        component: 'components/version/index',
        hideInMenu: true,
      },      
      {
        parentId: 1,
        id: 4,
        name: 'default',
        icon: '',
        path: '/components/default',
        component: 'components/project/index',
      },      
    ],
  },

  {
    parentId: 0,
    id: 9,
    name: 'accounts',
    icon: '',
    path: '/accounts',
    component: '',
    routes: [
      {
        parentId: 9,
        id: 10,
        name: 'user',
        icon: '',
        path: '/accounts/user',
        component: 'authorization/user/index',
      },
    ],
  },

  {
    parentId: 0,
    id: 100,
    name: 'system',
    icon: '',
    path: '/system',
    component: '',
    routes: [
      {
        parentId: 100,
        id: 101,
        name: 'about',
        icon: '',
        path: '/system/about',
        component: 'system/about/index',        
      },
      {
        parentId: 100,
        id: 102,
        name: 'license',
        icon: '',
        path: '/system/license',
        component: 'system/license/index',
      },
      {
        parentId: 100,
        id: 103,
        name: 'database',
        icon: '',
        path: '/system/database',
        component: 'system/database/index',
      },
      {
        parentId: 100,
        id: 104,
        name: 'logs',
        icon: '',
        path: '/system/logs',
        component: 'system/logs/index',
      },
      {
        parentId: 100,
        id: 105,
        name: 'cache',
        icon: '',
        path: '/system/cache',
        component: 'system/cache/index',
      },
      {
        parentId: 100,
        id: 110,
        name: 'services',
        icon: '',
        path: '/system/services',
        component: 'system/service/index',
      },
      {
        parentId: 100,
        id: 111,
        name: 'queues',
        icon: '',
        path: '/system/queues',
        component: 'system/queue/index',
      },
      {
        parentId: 100,
        id: 112,
        name: 'version',
        icon: '',
        path: '/system/versions',
        component: 'system/version/index',
      },
      {
        parentId: 100,
        id: 113,
        name: 'jobs',
        icon: '',
        path: '/system/jobs',
        component: 'system/job/index',
      },
      {
        parentId: 100,
        id: 114,
        name: 'version-detail',
        icon: '',
        path: '/system/version/:vid',
        component: 'system/version-detail/index',
        hideInMenu: true,
      },
    ],
  },
  {
    parentId: 0,
    id: 200,
    name: 'helpcenter',
    icon: '',
    path: '/helpcenter',
    component: '',
    routes: [      
      {
        parentId: 200,
        id: 201,
        name: 'tips',
        icon: '',
        path: '/helpcenter/tips',
        component: 'helpcenter/tips/index',
      },
      {
        parentId: 200,
        id: 202,
        name: 'cwe',
        icon: '',
        path: '/helpcenter/cwes',
        component: 'helpcenter/cwe/index',
      },
      {
        parentId: 200,
        id: 203,
        name: 'cwe-detail',
        icon: '',
        path: '/helpcenter/cwe/:id',
        component: 'helpcenter/cwe-detail/index',        
        hideInMenu: true,
      },      
      {
        parentId: 200,
        id: 204,
        name: 'license',
        icon: '',
        path: '/helpcenter/licenses',
        component: 'helpcenter/license/index',
      },
      {
        parentId: 200,
        id: 205,
        name: 'license-detail',
        icon: '',
        path: '/helpcenter/license/:id',
        component: 'helpcenter/license-detail/index',        
        hideInMenu: true,
      },
      
      {
        parentId: 200,
        id: 210,
        name: 'vulnerability',
        icon: '',
        path: '/helpcenter/vulnerabilities',
        component: 'helpcenter/vulnerability/index',
      },
      {
        parentId: 200,
        id: 211,
        name: 'vulnerability-detail',
        icon: '',
        path: '/helpcenter/vulnerability/:id',
        component: 'helpcenter/vulnerability-detail/index',        
        hideInMenu: true,
      },      
      {
        parentId: 200,
        id: 212,
        name: 'package-vulnerabilities',
        icon: '',
        path: '/helpcenter/package/vulnerabilities',
        component: 'helpcenter/package-vulnerabilities/index',
      },

      {
        parentId: 200,
        id: 220,
        name: 'exploit',
        icon: '',
        path: '/helpcenter/exploits',
        component: 'helpcenter/exploit/index',
      },
      {
        parentId: 200,
        id: 221,
        name: 'exploit-detail',
        icon: '',
        path: '/helpcenter/exploit/:id',
        component: 'helpcenter/exploit-detail/index',        
        hideInMenu: true,
      },
    ],
  },
  {
    parentId: 0,
    id: 300,
    name: 'monitor',
    icon: '',
    path: '/monitor',
    component: '',
    routes: [      
      {
        parentId: 300,
        id: 301,
        name: 'updated-events',
        icon: '',
        path: '/monitor/updated-events',
        component: 'monitor/updated-events/index',
      },
      {
        parentId: 300,
        id: 302,
        name: 'version-events',
        icon: '',
        path: '/monitor/version-events',
        component: 'monitor/version-events/index',
      },
      {
        parentId: 300,
        id: 303,
        name: 'event-detail',
        icon: '',
        path: '/monitor/event/:id',
        component: 'monitor/event-detail/index',
        hideInMenu: true,
      },
    ],
  },
];
